#!/bin/sh

chvt 1

rmmod ehci-hcd

rmmod uhci-hcd

echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

#echo 3 > /proc/acpi/sleep
echo platform > /sys/power/disk
echo mem > /sys/power/state

echo powersave > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

/usr/sbin/boot-radeon

modprobe uhci-hcd

modprobe ehci-hcd

chvt 7

