#!/bin/sh

. "${PM_FUNCTIONS}"

suspend_FPS() {
    # Signal the vcsFPService about the suspend/hiberante
	if pgrep vcsFPService > /dev/null ; then
		echo " Sending Suspend Event"
		pkill -SIGUSR1 vcsFPService
	fi
}

resume_FPS() {
	# Signal the vcsFPService about the resume
	if pgrep vcsFPService > /dev/null ; then
		pkill -SIGUSR2 vcsFPService
	fi
}

case "$1" in
	thaw|resume)
		resume_FPS
		;;
	hibernate|suspend)
		suspend_FPS
		;;
	*)
		exit $NA
		;;
esac
